config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    root to: "posts#index"
   end 

  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/project' => 'high_voltage/pages#show', id: 'projects'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/blog'    => 'high_voltage/pages#show', id: 'blogs'

  get '/home', to: redirect('/')

  root :to => 'high_voltage/pages#show', id: 'home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(params[:comments])
  	@comment.save

  	redirect_to @post
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

  	redirect_to @comment.post
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def blogs
	   @posts = Post.all
   end
end   
	   

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @posts }
      format.atom
    end

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

      if @post.save
         redirect_to @post, notice: 'Post was successfully created.' 
      else
         render action: 'new'
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def site_name
    # Change the value below between the quotes.
    "SEI"
  end

  def site_url
    if Rails.env.production?
      # Place your production URL in the quotes below
      "http://http://www.example.com/"
    else
      # Our dev & test URL
      "http://localhost:3000"
    end
  end

  def meta_author
    # Change the value below between the quotes.
    "Van Berti"
  end

  def meta_description
    # Change the value below between the quotes.
    "Social Enterprise Investments"
  end

  def meta_keywords
    # Change the value below between the quotes.
    "Social"
  end

  # Returns the full title on a per-page basis.
  # No need to change any of this we set page_title and site_name elsewhere.
  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!-- kl.<!DOCTYPE html> -->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">

  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="style.css.scss" />
  <%= content_for :head %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>
  
  <%= content_for :head, auto_discovery_link_tag(:atom, posts_url(format: "atom")) %>

</head>
  
<body>

  <div id="wrapper">
    <div id="header">
      <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to site_name, site_url, :class => "navbar-brand" %>
          </div><!-- /.navbar-header -->

          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">
              <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
              <li class="<%= 'active' if current_page?(project_path) %>"><%= link_to "Projects", project_path %></li>
              <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About Us", about_path %></li>
              <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
              <li class="<%= 'active' if current_page?(blog_path) %>"><%= link_to "Blogs", blog_path %></li>
              <!-- <li><%= link_to "Manage Posts", posts_url %></li> -->
            </ul>
          </div><!-- /.nav-collapse -->
        </div><!-- /.container -->
      </div><!-- /.navbar -->
    </div><!-- /#header -->
    
    <div id="content">
      <% if current_page?(root_path) %>
       <% if content_for?(:jumbotron) %>
         <div class="jumbotron">
           <div class="container">
             <%= yield :jumbotron %>
           </div><!-- /container -->
         </div><!-- jumbotron -->
       <% end %><!-- jumbotron -->
      <% else %>
        <div class="container">
        </div>
      <% end %><!-- current-page -->

      <%= yield %>
    </div><!-- content -->

    <div id="end-footer">
      
        
          <div class="container">
            <div class="row">
              <div class="span12">
                <p>&copy; SEI Pty Ltd <span id="totop" class="pull-right">Back to Top</span></p>
              </div><!-- /span12 -->
            </div><!-- /row -->
          </div><!-- /container -->
        
      
    </div><!-- /end-footer -->
  </div><!-- #wrapper -->

 </body>
</html>

app/views/pages/about.html.erb
<html>
  <head>
    <title>About SEI</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>

           <h1>About Us</h1>
           <div class="jumbotron-landing">
           </div>

</body>
</html>

app/views/pages/aim.html.erb
<html>
  <head>
    <title>Aims of SEI</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>

         <div class="container">
           <h1>Our Aim</h1>
           <p>Social Enterprise Investments aim is to achieve continuous growth and ever increasing market exposure , and become a leading and highly valued social enterprise business through the promotion and development of new business and philanthropic  initiatives, without compromising our personal approach and boutique feel. <br/><br/>

		   A truly focused social enterprise business, Social Enterprise Investments (SEI) is based on altruistic philosophies and, established so as to   offer a fully integrated support network to nurture and grow business and social community needs. Our ethos stems from its people and underpinned by proven business success and supported by a global team of visionaries, entrepeneurs and selected professionals partnered to support the success of exisitng and new initiatives by building a truly unique competitive advantage for today and omorrow. Social Enterprise Investments promotes the development of new initiatives and incubator projects that create value and offer new exciting opportunities for business to expand. We are committed to sustainable, ethical socio-economic growth and opportunity creation, and our hallmark is to create a true partneship, which means getting to know business partners meticulously and understanding their business and creating market opportunities and value. </p>
		</div>


</body>
</html>

app/views/pages/blogs.html.erb
<html>
  <head>
    <title>Blogs</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>

           <h1>Let's start talking</h1>

</body>
</html>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<div class="alt2">
    <div class="container">
      <br/>
      <h1>Contact Us</h1><br/>
      <form role="form">
        <div class="form-group">
          <label for="email">Email:</label>
          <input type="email" class="form-control" id="email" name="email" placeholder="example@example.com"/>
        </div>

        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" class="form-control" id="name" name="name" placeholder="Your name here"/>
        </div>
          
        <div class="form-group">
          <label for="message">Message:</label>
          <textarea class="form-control" name="message" id="message" placeholder="Your message here"></textarea>
        </div>
        <div class="form-group">
          <input type="checkbox" /> Send me promotional content
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div>
  </div>

app/views/pages/home.html.erb
<html>
   
  <head>
    <title>Social Enterprise Investments</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
      <br/><br/>
      <div class="jumbotron">
        <div class="container">
<<<<<<< HEAD
          <h2> Social Enterprise Investments</h2>
=======
          <h2> Social Enterprise Investments </h2>
>>>>>>> 3843b498875c6c6f3807bb920797d6675b1bbc58
            <h5 class="heading5">A facilitator and investor in Ethically Sustainable & </h5>
            <h5 class="heading5a">Socially Responsible Enterprises</h5>
            <div class="heading" ><h3>'treating all stackholders fairly'.</h3></div>
        </div>
      </div>
          
      <div class="container"><br/>
        <h3 class="text-center">Our Ethos </h3>
        <p class="text-center">Social Enterprise Investments aim is to achieve continuous growth and ever increasing market exposure , and to become a leading and highly valued social enterprise business through the promotion and development of new business and philanthropic  initiatives, without compromising our personal approach and boutique feel.</p>
      </div>
      <br/><br/>
     
    

</body>
</html>

app/views/pages/inspiration.html.erb
<html>
  <head>
    <title>Aims of SEI</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>

           <h1>Inspiration</h1>

</body>
</html>

app/views/pages/people.html.erb
<html>
  <head>
    <title>Aims of SEI</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>

           <h1>People</h1>

</body>
</html>

app/views/pages/privacy.html.erb
<% provide(:title, 'Privacy Policy') %>
<h1>Privacy Policy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/projects.erb
  <div class="alt3">
  	<br/><br/>
   	<div class="jumbotron-landing">
    	<div class="container">
    	<!-- Example row of columns -->
    	<div class="row">
      		<div class="col-md-4">
       		 <h2 class="text-center">African Australian Cooperative</h2>
       		 <h3>Mining & Commodities Ventures</h3>
        	 <p class="text-center">Mining Sector initiative and investment capital<br/>
				Textile Sector initiatives<br/>Agricultural Sector initiatives<br/>Building technologies
				<br/>Construction</p><br/>
        	 <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      		</div>
      		<div class="col-md-4">
        		<h2 class="text-center">African Australian Alliance</h2>
        		<h4> Cultural, technological and enterprise transfer</h4>
        		<p class="text-justify">Social Enterprise Investments ( SEI) is partnered with African Australian Cooperative to build and operate a leading development and educational facility providing work and community development, and enabling young students to gain the necessary skills, values and attitude to grow and  make a positive difference to society. </p>
       	 		<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
     		</div>
      		<div class="col-md-4">
        		<h2 class="text-center">Magic Delights</h2>
        		<h4> Your patisserie artisan creating healthy food</h4>
        		<p class="text-center">"We love healthy cakes and biscuits."<br/>
					"Setting the trend for young and old alike"</p><br/><br/><br/><br/>
        		<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      		</div>
    	</div>
   	 </div>
   	</div>

   	<br/><br/>
   	<div class="jumbotron-landing">
    	<div class="container">
    	<!-- Example row of columns -->
    	<div class="row">
      		<div class="col-md-4">
       		 <h2 class="text-center">Strategic On line Software</h2>
       		 <h3>Partnering your on line presence</h3>
        	 <p class="text-center">Smart web site development<br/>Application Development<br/><br/><br/><br/><br/><br/><br/>
        	 <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      		</div>
      		<div class="col-md-4">
        		<h2 class="text-center">SMESauce</h2>
        		<h3> your Enterprise Service Provider</h3>
        		<p class="text-justify">• Integrating technology to better serve businesses.<br/>
				• Business Analysis, Product and Service Planning and Marketing, Financial Management services tailored for ongoing business success.<br/>
				• Business Improvement Initiatives, enhancements and  organisational improvements to sustain and promote growth.</p><br/>
       	 		<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
     		</div>
      		<div class="col-md-4">
        		<h2 class="text-center">Rags to Brag</h2>
        		<h3> Socially responsible fashion</h3>
        		<p class="text-center">Source materials<br/>Fashionista<br/>Design<br/>Distribution<br/>Marketing<br/>International<br/>Couture<br/>Fusion of design</p>
        		<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      		</div>
    	</div>
   	 </div>
   	</div>
   </div>

app/views/pages/terms.html.erb
<% provide(:title, 'Terms of Service') %>
<h1>Terms of Service</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/pages/vision.html.erb
<html>
  <head>
    <title>Aims of SEI</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>

           <h1>You are now in the Vision page.</h1>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'form_control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>Listing Posts</h2>

<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Content</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @posts.each do |post| %>
		  <tr>
  			<td><%= post.title %></td>
  			<td><%= truncate(post.text, length: 100) %></td>
  			<td><%= link_to 'Show', post %></td>
  			<td><%= link_to 'Edit', edit_post_path(post) %></td>
  			<td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  		  </tr>
  		<% end %>
  	</tbody>
</table>

<br/>

<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<br/><br/><br/><br/><br/>
<% if notice.present? %>
  <p class="alert alert-info">
	  <%=notice %>
  </p>
 <% end %>

<p>
  	<h2>	
	<%= @post.title %>
	</h2>
</p>
<p>	
	<%= simple_format @post.text %>
</p>

<p class="text-muted">
	<small>Posted on <%= @post.created_at.to_formatted_s(:long) %></small>
</p>

<h2>Comments</h2>

<% @post.comments.each do |comment| %>
	<p><%= comment.text %></p>
	<p><%= time_ago_in_words comment.created_at %> ago</p>
	<p><%= link_to "Delete comment", [@post, comment], :method => :delete, :confirm => "Are you sure?" %></p>
<% end %>	

<%= form_for [@post, @post.comments.build] do |f| %>
	<p><%= f.text_area :text, :size => '40*10' %></p>
	<p><%= f.submit "Post comment" %></p>
<% end %>